# Generated by Django 3.2.16 on 2023-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/user'),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
