# Generated by Django 3.2.16 on 2023-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
