# Generated by Django 3.2.16 on 2023-04-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0002_auto_20230414_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='barslist',
            name='fadebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='barslist',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
