# Generated by Django 3.2.16 on 2023-04-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0003_auto_20230414_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barslist',
            old_name='bar_name',
            new_name='post',
        ),
    ]
