# Generated by Django 3.2.16 on 2023-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0003_bar_barreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='name',
            new_name='bar_name',
        ),
        migrations.RenameField(
            model_name='barreview',
            old_name='bar',
            new_name='bar_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='bar',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
