# Generated by Django 3.2.16 on 2023-01-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0004_auto_20230118_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barreview',
            name='title',
        ),
    ]
