# Generated by Django 3.2.16 on 2023-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berlin_bestbeers', '0005_remove_barreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bar',
            name='bar_name',
            field=models.CharField(max_length=100),
        ),
    ]
